CONTIKI = ../..
DEFINES = RF_CHANNEL=26, NETSTACK_CONF_MAC=csma_driver, NETSTACK_CONF_RDC=nullrdc_driver, QUEUEBUF_CONF_NUM=30
all: example-abc example-mesh example-collect example-trickle example-polite \
     example-rudolph0 example-rudolph1 example-rudolph2 example-rucb \
     example-runicast example-unicast example-neighbors ctp_pradipta

include $(CONTIKI)/Makefile.include
